/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageSchema {
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "text")]
    pub text: String,
}

impl MessageSchema {
    pub fn new(role: String, text: String) -> MessageSchema {
        MessageSchema {
            role,
            text,
        }
    }
}

