/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlotResponseSchema {
    #[serde(rename = "plot")]
    pub plot: String,
}

impl PlotResponseSchema {
    pub fn new(plot: String) -> PlotResponseSchema {
        PlotResponseSchema { plot }
    }
}
