# Generated by Django 5.1.2 on 2024-10-27 05:19

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corpora", "0001_enable_vector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Corpus",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for each corpus, used as the primary key.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL associated with the corpus, e.g., a GitHub repository.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp indicating when the corpus was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp indicating the last update of the corpus.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "corpora",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("content", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "vector_of_summary",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=300, null=True
                    ),
                ),
                ("checksum", models.CharField(editable=False, max_length=32)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="corpora.corpus",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "unique_together": {("corpus", "path")},
            },
        ),
        migrations.CreateModel(
            name="Split",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("content", models.TextField(blank=True)),
                (
                    "vector",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=300, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="corpora.file",
                    ),
                ),
            ],
            options={
                "ordering": ["file", "order"],
                "unique_together": {("file", "order")},
            },
        ),
    ]
