# Generated by Django 5.1.2 on 2024-10-27 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="owner",
            field=models.ForeignKey(
                default=1,
                help_text="User who owns the corpus.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corpora",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
