# Generated by Django 5.1.2 on 2024-11-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0003_corpus_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="checksum",
            field=models.CharField(
                editable=False,
                help_text="SHA1 checksum of the file content as in `git hash-object`",
                max_length=40,
            ),
        ),
    ]
