# Generated by Django 5.1.2 on 2024-11-03 02:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0004_alter_file_checksum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="corpus",
            unique_together={("name", "owner")},
        ),
    ]
