# Generated by Django 5.1.2 on 2024-11-04 01:41

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0006_rename_file_corpustextfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="split",
            name="vector",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="text-embedding-3-small vector of the content",
                null=True,
            ),
        ),
    ]
