# Generated by Django 5.1.2 on 2024-11-04 02:58

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0007_alter_split_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpustextfile",
            name="vector_of_summary",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="text-embedding-3-small vector of the content",
                null=True,
            ),
        ),
    ]
