# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.api.file_api import FileApi


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FileApi()

    def tearDown(self) -> None:
        pass

    def test_create_file(self) -> None:
        """Test case for create_file

        Create File
        """
        pass

    def test_get_file(self) -> None:
        """Test case for get_file

        Get File
        """
        pass

    def test_get_file_by_path(self) -> None:
        """Test case for get_file_by_path

        Get File By Path
        """
        pass


if __name__ == "__main__":
    unittest.main()
