# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.models.corpus_update_files_schema import CorpusUpdateFilesSchema


class TestCorpusUpdateFilesSchema(unittest.TestCase):
    """CorpusUpdateFilesSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorpusUpdateFilesSchema:
        """Test CorpusUpdateFilesSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CorpusUpdateFilesSchema`
        """
        model = CorpusUpdateFilesSchema()
        if include_optional:
            return CorpusUpdateFilesSchema(
                delete_files = [
                    ''
                    ]
            )
        else:
            return CorpusUpdateFilesSchema(
        )
        """

    def testCorpusUpdateFilesSchema(self):
        """Test CorpusUpdateFilesSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
