# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.models.corpus_chat_schema import CorpusChatSchema

class TestCorpusChatSchema(unittest.TestCase):
    """CorpusChatSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorpusChatSchema:
        """Test CorpusChatSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorpusChatSchema`
        """
        model = CorpusChatSchema()
        if include_optional:
            return CorpusChatSchema(
                corpus_id = '',
                messages = [
                    corpora_client.models.message_schema.MessageSchema(
                        role = '', 
                        text = '', )
                    ],
                voice = '',
                purpose = '',
                structure = '',
                directions = ''
            )
        else:
            return CorpusChatSchema(
                corpus_id = '',
                messages = [
                    corpora_client.models.message_schema.MessageSchema(
                        role = '', 
                        text = '', )
                    ],
        )
        """

    def testCorpusChatSchema(self):
        """Test CorpusChatSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
