# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.api.corpus_api import CorpusApi


class TestCorpusApi(unittest.TestCase):
    """CorpusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CorpusApi()

    def tearDown(self) -> None:
        pass

    def test_corpora_routers_corpus_create_corpus(self) -> None:
        """Test case for corpora_routers_corpus_create_corpus

        Create Corpus
        """
        pass

    def test_corpora_routers_corpus_delete_corpus(self) -> None:
        """Test case for corpora_routers_corpus_delete_corpus

        Delete Corpus
        """
        pass

    def test_corpora_routers_corpus_get_corpus(self) -> None:
        """Test case for corpora_routers_corpus_get_corpus

        Get Corpus
        """
        pass

    def test_corpora_routers_corpus_list_corpora(self) -> None:
        """Test case for corpora_routers_corpus_list_corpora

        List Corpora
        """
        pass


if __name__ == "__main__":
    unittest.main()
