# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.api.corpus_api import CorpusApi


class TestCorpusApi(unittest.TestCase):
    """CorpusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CorpusApi()

    def tearDown(self) -> None:
        pass

    def test_create_corpus(self) -> None:
        """Test case for create_corpus

        Create Corpus
        """
        pass

    def test_delete_corpus(self) -> None:
        """Test case for delete_corpus

        Delete Corpus
        """
        pass

    def test_delete_files(self) -> None:
        """Test case for delete_files

        Delete Files
        """
        pass

    def test_get_corpus(self) -> None:
        """Test case for get_corpus

        Get Corpus
        """
        pass

    def test_get_file_hashes(self) -> None:
        """Test case for get_file_hashes

        Get File Hashes
        """
        pass

    def test_list_corpora(self) -> None:
        """Test case for list_corpora

        List Corpora
        """
        pass

    def test_update_files(self) -> None:
        """Test case for update_files

        Update Files
        """
        pass


if __name__ == "__main__":
    unittest.main()
