# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.models.split_vector_search_schema import SplitVectorSearchSchema


class TestSplitVectorSearchSchema(unittest.TestCase):
    """SplitVectorSearchSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SplitVectorSearchSchema:
        """Test SplitVectorSearchSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SplitVectorSearchSchema`
        """
        model = SplitVectorSearchSchema()
        if include_optional:
            return SplitVectorSearchSchema(
                corpus_id = '',
                vector = [
                    1.337
                    ],
                limit = 56
            )
        else:
            return SplitVectorSearchSchema(
                corpus_id = '',
                vector = [
                    1.337
                    ],
        )
        """

    def testSplitVectorSearchSchema(self):
        """Test SplitVectorSearchSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
