# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.api.plots_api import PlotsApi


class TestPlotsApi(unittest.TestCase):
    """PlotsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlotsApi()

    def tearDown(self) -> None:
        pass

    def test_get_matplotlib_plot(self) -> None:
        """Test case for get_matplotlib_plot

        Get Matplotlib Plot
        """
        pass


if __name__ == '__main__':
    unittest.main()
