# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.models.file_schema import FileSchema

class TestFileSchema(unittest.TestCase):
    """FileSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileSchema:
        """Test FileSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileSchema`
        """
        model = FileSchema()
        if include_optional:
            return FileSchema(
                path = '',
                content = '',
                corpus_id = ''
            )
        else:
            return FileSchema(
                path = '',
                content = '',
                corpus_id = '',
        )
        """

    def testFileSchema(self):
        """Test FileSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
