# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.models.issue_request_schema import IssueRequestSchema


class TestIssueRequestSchema(unittest.TestCase):
    """IssueRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IssueRequestSchema:
        """Test IssueRequestSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `IssueRequestSchema`
        """
        model = IssueRequestSchema()
        if include_optional:
            return IssueRequestSchema(
                corpus_id = '',
                messages = [
                    corpora_client.models.message_schema.MessageSchema(
                        role = '', 
                        text = '', )
                    ],
                voice = '',
                purpose = '',
                structure = '',
                directions = ''
            )
        else:
            return IssueRequestSchema(
                corpus_id = '',
                messages = [
                    corpora_client.models.message_schema.MessageSchema(
                        role = '', 
                        text = '', )
                    ],
        )
        """

    def testIssueRequestSchema(self):
        """Test IssueRequestSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
