# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.api.corpora_api import CorporaApi


class TestCorporaApi(unittest.TestCase):
    """CorporaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CorporaApi()

    def tearDown(self) -> None:
        pass

    def test_corpora_api_create_corpus(self) -> None:
        """Test case for corpora_api_create_corpus

        Create Corpus
        """
        pass

    def test_corpora_api_create_file(self) -> None:
        """Test case for corpora_api_create_file

        Create File
        """
        pass

    def test_corpora_api_get_corpus(self) -> None:
        """Test case for corpora_api_get_corpus

        Get Corpus
        """
        pass

    def test_corpora_api_get_file(self) -> None:
        """Test case for corpora_api_get_file

        Get File
        """
        pass

    def test_corpora_api_list_corpora(self) -> None:
        """Test case for corpora_api_list_corpora

        List Corpora
        """
        pass


if __name__ == "__main__":
    unittest.main()
