# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.api.splits_api import SplitsApi


class TestSplitsApi(unittest.TestCase):
    """SplitsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SplitsApi()

    def tearDown(self) -> None:
        pass

    def test_corpora_routers_split_get_split(self) -> None:
        """Test case for corpora_routers_split_get_split

        Get Split
        """
        pass

    def test_corpora_routers_split_list_splits_for_file(self) -> None:
        """Test case for corpora_routers_split_list_splits_for_file

        List Splits For File
        """
        pass

    def test_corpora_routers_split_vector_search_splits(self) -> None:
        """Test case for corpora_routers_split_vector_search_splits

        Vector Search Splits
        """
        pass


if __name__ == "__main__":
    unittest.main()
