# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.models.plot_response_schema import PlotResponseSchema

class TestPlotResponseSchema(unittest.TestCase):
    """PlotResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlotResponseSchema:
        """Test PlotResponseSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlotResponseSchema`
        """
        model = PlotResponseSchema()
        if include_optional:
            return PlotResponseSchema(
                plot = ''
            )
        else:
            return PlotResponseSchema(
                plot = '',
        )
        """

    def testPlotResponseSchema(self):
        """Test PlotResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
