# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.api.workon_api import WorkonApi


class TestWorkonApi(unittest.TestCase):
    """WorkonApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkonApi()

    def tearDown(self) -> None:
        pass

    def test_file(self) -> None:
        """Test case for file

        File
        """
        pass


if __name__ == "__main__":
    unittest.main()
