# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.models.update_corpus_schema import UpdateCorpusSchema


class TestUpdateCorpusSchema(unittest.TestCase):
    """UpdateCorpusSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCorpusSchema:
        """Test UpdateCorpusSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UpdateCorpusSchema`
        """
        model = UpdateCorpusSchema()
        if include_optional:
            return UpdateCorpusSchema(
                delete_files = [
                    ''
                    ]
            )
        else:
            return UpdateCorpusSchema(
        )
        """

    def testUpdateCorpusSchema(self):
        """Test UpdateCorpusSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
