# coding: utf-8

"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corpora_client.api.plan_api import PlanApi


class TestPlanApi(unittest.TestCase):
    """PlanApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlanApi()

    def tearDown(self) -> None:
        pass

    def test_get_issue(self) -> None:
        """Test case for get_issue

        Get Issue
        """
        pass


if __name__ == "__main__":
    unittest.main()
