# coding: utf-8

# flake8: noqa
"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from corpora_client.models.corpus_response_schema import CorpusResponseSchema
from corpora_client.models.corpus_schema import CorpusSchema
from corpora_client.models.file_response_schema import FileResponseSchema
from corpora_client.models.file_schema import FileSchema
from corpora_client.models.split_response_schema import SplitResponseSchema
from corpora_client.models.split_vector_search_schema import SplitVectorSearchSchema
