# coding: utf-8

# flake8: noqa
"""
    Corpora API

    API for managing and processing corpora

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from corpora_client.models.corpus_chat_schema import CorpusChatSchema
from corpora_client.models.corpus_file_chat_schema import CorpusFileChatSchema
from corpora_client.models.corpus_response_schema import CorpusResponseSchema
from corpora_client.models.corpus_schema import CorpusSchema
from corpora_client.models.corpus_update_files_schema import CorpusUpdateFilesSchema
from corpora_client.models.file_response_schema import FileResponseSchema
from corpora_client.models.file_schema import FileSchema
from corpora_client.models.issue_schema import IssueSchema
from corpora_client.models.message_schema import MessageSchema
from corpora_client.models.plot_response_schema import PlotResponseSchema
from corpora_client.models.split_response_schema import SplitResponseSchema
from corpora_client.models.split_vector_search_schema import SplitVectorSearchSchema
